# Try to find the GMP librairies
#  GTEST_FOUND - system has GTEST
#  GTEST_INCLUDE_DIR - the GMP include directory

IF (GTEST_INCLUDE_DIR)
  SET(GTEST_FIND_QUIETLY TRUE)
endif (GTEST_INCLUDE_DIR)

FIND_PATH(GTEST_INCLUDE_DIR NAMES gtest.h PATH gtest)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GTEST DEFAULT_MSG GTEST_INCLUDE_DIR)
